# Generated by Django 5.0.14 on 2026-02-14 16:06

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DeliverySlot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField(help_text='Delivery date')),
                ('start_time', models.TimeField(help_text='Start time of delivery window')),
                ('end_time', models.TimeField(help_text='End time of delivery window')),
                ('max_capacity', models.IntegerField(help_text='Maximum number of orders for this slot')),
                ('current_count', models.IntegerField(default=0, help_text='Current number of booked orders')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this slot is available for booking')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'delivery_slots',
                'ordering': ['date', 'start_time'],
                'indexes': [models.Index(fields=['date', 'start_time'], name='delivery_sl_date_090996_idx'), models.Index(fields=['is_active', 'date'], name='delivery_sl_is_acti_633ec5_idx')],
                'unique_together': {('date', 'start_time', 'end_time')},
            },
        ),
        migrations.CreateModel(
            name='DeliverySlotException',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField(help_text='Date to block deliveries')),
                ('reason', models.CharField(help_text='Reason for blocking', max_length=200)),
                ('is_blocked', models.BooleanField(default=True, help_text='Whether deliveries are blocked on this date')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'delivery_slot_exceptions',
                'unique_together': {('date',)},
            },
        ),
    ]
