# Generated by Django 5.0.14 on 2026-02-07 15:18

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(db_index=True, help_text='唯一優惠碼 (如: SUPERMARKET666)', max_length=50, unique=True)),
                ('discount_type', models.CharField(choices=[('PERCENTAGE', '百分比折扣'), ('FIXED_AMOUNT', '固定金額折扣')], help_text='折扣類型', max_length=20)),
                ('discount_value', models.DecimalField(decimal_places=2, help_text='折扣數值（百分比為 0-100，固定金額為實際金額）', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('min_purchase_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='最低消費金額門檻', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('valid_from', models.DateTimeField(help_text='生效時間')),
                ('valid_until', models.DateTimeField(help_text='失效時間')),
                ('total_limit', models.PositiveIntegerField(default=0, help_text='總共可使用次數 (0 = 無限制)')),
                ('used_count', models.PositiveIntegerField(default=0, help_text='已使用次數 (Ref: data.md §1E - 必須用 F() 更新)')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='手動啟用/停用開關')),
            ],
            options={
                'verbose_name': 'Coupon',
                'verbose_name_plural': 'Coupons',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('PENDING', '待付款'), ('PAID', '已付款'), ('SHIPPED', '已發貨'), ('CANCELLED', '已取消'), ('REFUNDED', '已退款')], db_index=True, default='PENDING', help_text='訂單狀態', max_length=20)),
                ('total_amount', models.DecimalField(decimal_places=2, help_text='訂單總金額（折扣後）', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('payment_id', models.CharField(blank=True, help_text='支付憑證 ID (Ref: data.md §1C)', max_length=100)),
                ('discount_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='折扣金額 (Ref: data.md §1E - 記錄下單時的折扣額度)', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('applied_coupon', models.ForeignKey(blank=True, help_text='使用的優惠碼 (Ref: data.md §1E - 必須記錄)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='orders.coupon')),
                ('user', models.ForeignKey(help_text='下單用戶', on_delete=django.db.models.deletion.PROTECT, related_name='orders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Order',
                'verbose_name_plural': 'Orders',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quantity', models.PositiveIntegerField(help_text='購買數量', validators=[django.core.validators.MinValueValidator(1)])),
                ('price_at_purchase', models.DecimalField(decimal_places=2, help_text='購買時價格 (Ref: data.md §1C - 防止調價影響歷史訂單)', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('order', models.ForeignKey(help_text='所屬訂單', on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.order')),
                ('product', models.ForeignKey(help_text='購買商品', on_delete=django.db.models.deletion.PROTECT, related_name='order_items', to='products.product')),
            ],
            options={
                'verbose_name': 'Order Item',
                'verbose_name_plural': 'Order Items',
            },
        ),
        migrations.CreateModel(
            name='UserCoupon',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('used_at', models.DateTimeField(blank=True, help_text='使用時間（null 表示已領取但未使用）', null=True)),
                ('coupon', models.ForeignKey(help_text='優惠碼', on_delete=django.db.models.deletion.CASCADE, related_name='user_coupons', to='orders.coupon')),
                ('user', models.ForeignKey(help_text='用戶', on_delete=django.db.models.deletion.CASCADE, related_name='user_coupons', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Coupon',
                'verbose_name_plural': 'User Coupons',
            },
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['user', '-created_at'], name='orders_orde_user_id_0ae59f_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['status', '-created_at'], name='orders_orde_status_079368_idx'),
        ),
        migrations.AddConstraint(
            model_name='usercoupon',
            constraint=models.UniqueConstraint(fields=('user', 'coupon'), name='unique_user_coupon'),
        ),
    ]
