# Generated by Django 5.0.14 on 2026-02-14 16:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0001_initial'),
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_slot',
            field=models.ForeignKey(blank=True, help_text='配送時段 (Ref: Delivery Slot Management)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='delivery.deliveryslot'),
        ),
    ]
