# Generated by Django 5.0.14 on 2026-02-07 14:51

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text='分類名稱', max_length=100)),
                ('slug', models.SlugField(help_text='URL 友好的唯一標識符', max_length=100, unique=True)),
                ('is_active', models.BooleanField(default=True, help_text='是否啟用此分類')),
                ('parent', models.ForeignKey(blank=True, help_text='父分類（用於多層分類結構）', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='products.category')),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text='商品名稱', max_length=200)),
                ('description', models.TextField(blank=True, help_text='商品描述')),
                ('price', models.DecimalField(decimal_places=2, help_text='商品價格 (Ref: data.md §4 - DecimalField)', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('image_url', models.URLField(blank=True, help_text='商品圖片 URL (Ref: infra.md §5 - 外部存儲)')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='是否上架（用於快速下架產品）')),
                ('category', models.ForeignKey(help_text='商品分類', on_delete=django.db.models.deletion.PROTECT, related_name='products', to='products.category')),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quantity', models.PositiveIntegerField(default=0, help_text='庫存數量')),
                ('version', models.PositiveIntegerField(default=0, help_text='樂觀鎖版本號 (Ref: data.md §1B - Optimistic Locking)')),
                ('product', models.OneToOneField(help_text='關聯商品', on_delete=django.db.models.deletion.CASCADE, related_name='stock', to='products.product')),
            ],
            options={
                'verbose_name': 'Stock',
                'verbose_name_plural': 'Stocks',
            },
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['is_active', '-created_at'], name='products_pr_is_acti_645007_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['category', 'is_active'], name='products_pr_categor_50f5f1_idx'),
        ),
    ]
